helm:
  parameters:
  - name: elasticsearch.image.repository
    value: docker.io/svmani218/elasticsearch
    forcestring: true
  - name: elasticsearch.image.tag
    value: 8.14.2
    forcestring: true
